stages:
  - build

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build-api-image:
  stage: build

  tags:
    - todolist-api-runner

  image: docker:27

  services:
    - docker:27-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

  script:
    - echo "Building API image..."
    - docker build -f src/TodoList.Api/Dockerfile -t $CI_REGISTRY_IMAGE/todolist-api:$IMAGE_TAG .
    - docker tag $CI_REGISTRY_IMAGE/todolist-api:$IMAGE_TAG $CI_REGISTRY_IMAGE/todolist-api:latest

    - echo "Pushing API image..."
    - docker push $CI_REGISTRY_IMAGE/todolist-api:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/todolist-api:latest

  only:
    - main
    - devops/backend-deployment

build-emailconsumer-image:
  stage: build

  tags:
    - todolist-api-runner

  image: docker:27

  services:
    - docker:27-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

  script:
    - echo "Building EmailConsumer image..."
    - docker build -f src/TodoList.EmailConsumer/Dockerfile -t $CI_REGISTRY_IMAGE/todolist-emailconsumer:$IMAGE_TAG .
    - docker tag $CI_REGISTRY_IMAGE/todolist-emailconsumer:$IMAGE_TAG $CI_REGISTRY_IMAGE/todolist-emailconsumer:latest

    - echo "Pushing EmailConsumer image..."
    - docker push $CI_REGISTRY_IMAGE/todolist-emailconsumer:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/todolist-emailconsumer:latest

  only:
    - main
    - devops/backend-deployment

build-nginx-image:
  stage: build

  tags:
    - todolist-api-runner

  image: docker:27

  services:
    - docker:27-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

  script:
    - echo "Building Nginx image..."
    - docker build -f nginx/Dockerfile -t $CI_REGISTRY_IMAGE/todolist-nginx:$IMAGE_TAG nginx
    - docker tag $CI_REGISTRY_IMAGE/todolist-nginx:$IMAGE_TAG $CI_REGISTRY_IMAGE/todolist-nginx:latest

    - echo "Pushing Nginx image..."
    - docker push $CI_REGISTRY_IMAGE/todolist-nginx:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/todolist-nginx:latest

  only:
    - main
    - devops/backend-deployment