services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: todolist-api_nginx
    ports:
      - "80:80"
    # VOLUMES DIHAPUS TOTAL UTK MENGHINDARI ERROR MOUNT
    depends_on:
      todolist-api:
        condition: service_started
    profiles:
      - app
    restart: unless-stopped
    networks:
      - backend
  todolist-api:
    build:
      context: .
      dockerfile: src/TodoList.Api/Dockerfile
    image: todolist-api:latest
    container_name: todolist-api
    # Ports ditutup dari luar agar tidak bypass Nginx
    # ports:
    #   - "5014:8080"
    profiles:
      - app
    env_file:
      - .env.${ASPNETCORE_ENVIRONMENT:-Development}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started # Diubah ke started supaya API tidak terblockir healthcheck
    restart: unless-stopped
    networks:
      - backend

  todolist-emailconsumer:
    build:
      context: .
      dockerfile: src/TodoList.EmailConsumer/Dockerfile
    image: todolist-emailconsumer:latest
    container_name: todolist-emailconsumer
    profiles:
      - app
      - email-consumer
    env_file:
      - .env.${ASPNETCORE_ENVIRONMENT:-Development}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_started # Diubah ke started agar consumer langsung stand-by
    networks:
      - backend

  postgres:
    image: postgres:15-alpine3.23
    container_name: todolist-api_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.${ASPNETCORE_ENVIRONMENT:-Development}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: todolist-api_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    env_file:
      - .env.${ASPNETCORE_ENVIRONMENT:-Development}
    restart: unless-stopped
    # Healthcheck tetap dipertahankan untuk monitoring status visual di 'docker ps'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 20s
    networks:
      - backend

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  backend:
    driver: bridge