# build stage
FROM dhi.io/dotnet:10-sdk-alpine3.24 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

# runtime stage
FROM dhi.io/aspnetcore:10-alpine3.24
WORKDIR /app

# copy from stage 1 build
COPY --from=build-env /app/out .

EXPOSE 8080

CMD ["dotnet", "TodoList.Api.dll"]