// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoList.Api.Infrastructure.DataContext;

#nullable disable

namespace TodoList.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoList.Api.Domain.Entities.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("emailverification_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailverification_createddate");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailverification_expiresat");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("emailverification_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("emailverification_userid");

                    b.HasKey("Id")
                        .HasName("pk_dbs001_emailverification");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_dbs001_emailverification_emailverification_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dbs001_emailverification_emailverification_userid");

                    b.ToTable("dbs001_emailverification", (string)null);
                });

            modelBuilder.Entity("TodoList.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("passwordresettoken_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passwordresettoken_createddate");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passwordresettoken_expiresat");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("passwordresettoken_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("passwordresettoken_userid");

                    b.HasKey("Id")
                        .HasName("pk_dbs001_passwordresettoken");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_dbs001_passwordresettoken_passwordresettoken_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dbs001_passwordresettoken_passwordresettoken_userid");

                    b.ToTable("dbs001_passwordresettoken", (string)null);
                });

            modelBuilder.Entity("TodoList.Api.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("todoitem_id");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("todoitem_completedDate");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("todoitem_createddate");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("todoitem_deleteddate");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("todoitem_description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("todoitem_isactive");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("todoitem_iscompleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("todoitem_title");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("todoitem_updateddate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("todoitem_userid");

                    b.HasKey("Id")
                        .HasName("pk_dbs001_todoitem");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dbs001_todoitem_todoitem_userid");

                    b.ToTable("dbs001_todoitem", (string)null);
                });

            modelBuilder.Entity("TodoList.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_createddate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_fullname");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("user_isemailverified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_passwordhash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_refreshtoken");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_refreshtokenexpiresat");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("user_updateddate");

                    b.HasKey("Id")
                        .HasName("pk_dbs001_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_dbs001_user_user_email");

                    b.ToTable("dbs001_user", (string)null);
                });

            modelBuilder.Entity("TodoList.Api.Domain.Entities.EmailVerification", b =>
                {
                    b.HasOne("TodoList.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dbs001_emailverification_dbs001_user_emailverification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoList.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("TodoList.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dbs001_passwordresettoken_dbs001_user_passwordresettoken_us");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoList.Api.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("TodoList.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dbs001_todoitem_dbs001_user_todoitem_userid");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
